### ISSUE TITLE
T5

### ISSUE THREAD

**Issue by jonathanstar** [dinkengraven/dinkengraven.github.io#27]
@programmerRD  I love Civ 5 (except when I play it I tend to do absolutely nothing productive for about 12 hours at a time.  Cool post.  Building a functional (but greatly restricted Civ 5 game would be a really fun and also maybe an attainable challenge for us in the near future.  My only feedback is that it might be cool to add more classes of things to demonstrate how they interact with each other.

**Comment by dinkengraven** [comment]
That's a great idea! Being a complete nut over Civ, it's very likely that I'll come back and do that at some point. Good luck to you at DBC!
